CREATE FUNCTION "classify"."try_parse_date"(value TEXT) RETURNS DATE AS $$
BEGIN
	RETURN value::DATE;
EXCEPTION WHEN OTHERS THEN
	RETURN NULL;
END;
$$ LANGUAGE PLPGSQL IMMUTABLE STRICT PARALLEL SAFE;
