CREATE TEMPORARY TABLE "category_data" ON COMMIT DROP AS
SELECT SUBSTRING("_key" FROM LENGTH('category:') + 1)::BIGINT "cid",
       "unique_string" "field",
       "value_string" "value"
  FROM "classify"."unclassified"
 WHERE "_key" SIMILAR TO 'category:[0-9]+'
   AND "type" = 'hash';

ALTER TABLE "category_data"
	ADD PRIMARY KEY ("cid", "field"),
	CLUSTER ON "category_data_pkey";

ANALYZE "category_data";

CREATE TABLE "classify"."categories" (
	-- structure
	"cid" BIGSERIAL,
	"slug" TEXT COLLATE "C" NOT NULL CHECK("slug" LIKE "cid" || '/%'),
	"parentCid" BIGINT,
	"order" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

	-- metadata
	"name" TEXT COLLATE "C" NOT NULL,
	"description" TEXT COLLATE "C" NOT NULL DEFAULT '',
	"descriptionParsed" TEXT COLLATE "C",
	"link" TEXT COLLATE "C",
	"disabled" BOOLEAN NOT NULL DEFAULT FALSE,
	"numRecentReplies" INT NOT NULL DEFAULT 1,

	-- style
	"color" TEXT COLLATE "C",
	"bgColor" TEXT COLLATE "C",
	"class" TEXT COLLATE "C",
	"icon" TEXT COLLATE "C",
	"image" TEXT COLLATE "C",
	"imageClass" TEXT COLLATE "C",

	-- counters
	"post_count" BIGINT NOT NULL DEFAULT 0,
	"topic_count" BIGINT NOT NULL DEFAULT 0,
	"timesClicked" BIGINT NOT NULL DEFAULT 0
) WITHOUT OIDS;

INSERT INTO "classify"."categories"
SELECT cid."unique_string"::BIGINT,
       slug."value",
       NULLIF(NULLIF(parentCid."value", ''), '0')::BIGINT,
       COALESCE(NULLIF(order_."value", ''), '0')::INT,
       name."value",
       COALESCE(description."value", ''),
       NULLIF(descriptionParsed."value", ''),
       NULLIF(link_."value", ''),
       COALESCE(NULLIF(disabled."value", ''), '0') = '1',
       COALESCE(NULLIF(numRecentReplies."value", ''), '1')::INT,
       color."value",
       bgColor."value",
       class."value",
       icon."value",
       image."value",
       imageClass."value",
       COALESCE(NULLIF(post_count."value", ''), '0')::BIGINT,
       COALESCE(NULLIF(topic_count."value", ''), '0')::BIGINT,
       COALESCE(NULLIF(timesClicked."value", ''), '0')::BIGINT
  FROM "classify"."unclassified" cid
  LEFT JOIN "category_data" slug
         ON slug."cid" = cid."unique_string"::BIGINT
        AND slug."field" = 'slug'
  LEFT JOIN "category_data" parentCid
         ON parentCid."cid" = cid."unique_string"::BIGINT
        AND parentCid."field" = 'parentCid'
  LEFT JOIN "category_data" order_
         ON order_."cid" = cid."unique_string"::BIGINT
        AND order_."field" = 'order'
  LEFT JOIN "category_data" name
         ON name."cid" = cid."unique_string"::BIGINT
        AND name."field" = 'name'
  LEFT JOIN "category_data" description
         ON description."cid" = cid."unique_string"::BIGINT
        AND description."field" = 'description'
  LEFT JOIN "category_data" descriptionParsed
         ON descriptionParsed."cid" = cid."unique_string"::BIGINT
        AND descriptionParsed."field" = 'descriptionParsed'
  LEFT JOIN "category_data" link_
         ON link_."cid" = cid."unique_string"::BIGINT
        AND link_."field" = 'link'
  LEFT JOIN "category_data" disabled
         ON disabled."cid" = cid."unique_string"::BIGINT
        AND disabled."field" = 'disabled'
  LEFT JOIN "category_data" numRecentReplies
         ON numRecentReplies."cid" = cid."unique_string"::BIGINT
        AND numRecentReplies."field" = 'numRecentReplies'
  LEFT JOIN "category_data" color
         ON color."cid" = cid."unique_string"::BIGINT
        AND color."field" = 'color'
  LEFT JOIN "category_data" bgColor
         ON bgColor."cid" = cid."unique_string"::BIGINT
        AND bgColor."field" = 'bgColor'
  LEFT JOIN "category_data" class
         ON class."cid" = cid."unique_string"::BIGINT
        AND class."field" = 'class'
  LEFT JOIN "category_data" icon
         ON icon."cid" = cid."unique_string"::BIGINT
        AND icon."field" = 'icon'
  LEFT JOIN "category_data" image
         ON image."cid" = cid."unique_string"::BIGINT
        AND image."field" = 'image'
  LEFT JOIN "category_data" imageClass
         ON imageClass."cid" = cid."unique_string"::BIGINT
        AND imageClass."field" = 'imageClass'
  LEFT JOIN "category_data" post_count
         ON post_count."cid" = cid."unique_string"::BIGINT
        AND post_count."field" = 'post_count'
  LEFT JOIN "category_data" topic_count
         ON topic_count."cid" = cid."unique_string"::BIGINT
        AND topic_count."field" = 'topic_count'
  LEFT JOIN "category_data" timesClicked
         ON timesClicked."cid" = cid."unique_string"::BIGINT
        AND timesClicked."field" = 'timesClicked'
 WHERE cid."_key" = 'categories:cid'
   AND cid."type" = 'zset';

\o /dev/null
SELECT setval('classify.categories_cid_seq', (
	SELECT "value_string"
	  FROM "classify"."unclassified"
	 WHERE "_key" = 'global'
	   AND "type" = 'hash'
	   AND "unique_string" = 'nextCid')::BIGINT);
\o

ALTER TABLE "classify"."categories"
	ADD PRIMARY KEY ("cid"),
	CLUSTER ON "categories_pkey";
CREATE INDEX ON "classify"."categories"("parentCid" NULLS FIRST, "order");
CREATE INDEX ON "classify"."categories"("disabled");
